### ISSUE TITLE
Halts at Importing Users WP4.3 [bbPress]

### ISSUE THREAD

**Issue by singhnsk** [a5mith/nodebb-plugin-import-wordpress#3]
There's something which is not right with the importer. I just gave it a run and it imports categories and the halts at importing users saying table not found.. I'm not known to coding, but still looking at it made me feel that it tries to access 'wp_users' table instead of using 'supplied prefix + users'.
I did try creating a new table with duplicate data as 'wp_users' but that didn't help either other than changing the error code to "{"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","index":0}"

Hope somebody can help sorting this out.

**Comment by tvsijin** [comment]
Dont u have a table called wp_users?

**Comment by singhnsk** [comment]
The modern bbPress plugins makes use of the users table of WordPress. What you're talking about was happening when bbpress was standalone. 
I don't have a wp_users table because my prefix is different. wp_[prefix]_users. 
However I did try to create a wp_users table and it halted still with the error mentioned in the original post.

**Comment by tvsijin** [comment]
i have made a small change in the script for you.. cant test since i dont have a similar environment
try to replace the node_modules/nodebb-plugin-import-wordpress/index.js with this new file https://github.com/tvsijin/nodebb-plugin-import-wordpress/blob/tvsijin-patch-1/index.js

**Comment by akhoury** [comment]
did you do follow this instruction?
https://github.com/a5mith/nodebb-plugin-import-wordpress#bbpress

Also, which bbpress version are you using? last tested was `bbpress 2.5.4` with `WordPress 4.0`

**Comment by singhnsk** [comment]
@akhoury 
Yes. I've followed the instructions correctly. I'm using Wordpress 4.3.1 and bbPress  2.5.8. I don't think that these version brought serious database changes and it should've worked out. Too bad, it didn't. Following is the exact log that appears:

Importing 0 users.

{"code":"ER_NO_SUCH_TABLE","errno":1146,"sqlState":"42S02","index":0}

current phase: usersImportStart

current phase: categoriesImportDone

Importing 4/4 categories took: 0.47 seconds

Importing 4 categories.

current phase: categoriesImportStart

current phase: groupsImportDone

Importing 0/0 groups took: 0.00 seconds

Importing 0 groups.

current phase: groupsImportStart

current phase: resetGlobalsDone

current phase: deleteTmpImportedSetsAndObjectsDone

current phase: deleteTmpImportedSetsAndObjectsStart

current phase: resetGlobalsStart

current phase: purgeMessagesDone

current phase: purgeMessagesStart

current phase: purgeUsersDone

current phase: purgeUsersStart

current phase: purgeCategories+Topics+PostsDone

current phase: purgeCategories+Topics+PostsStart

setup

**Comment by singhnsk** [comment]
Thanks to @tvsijin  there's some luck here.
I implemented your change, no luck. But then I noticed that you used + 'FROM wp_' + prefix + 'users '
This did not work out (call it my lack of explanation) because the prefix part does include wp_ as well. So I changed it to + 'FROM ' + prefix + 'users '

This did not work out, but instead made the importer skip users completely (imported 0 users) and it continued to import the other things. Now I have topics, categories, tags with proper date and time, unfortunately are posts are now marked as written by GUEST. 

Can be do something to fix the users importing? I think it won't be extremely tough for somebody familiar with coding. BTW, the final LOG was:

```
Done

teardown

current phase: importerComplete

current phase: importerTeardownDone

current phase: importerTeardownStart

Config restored:{"title":"NodeBB","showSiteTitle":"1","postDelay":"10","initialPostDelay":"10","newbiePostDelay":"120","newbiePostDelayThreshold":"3","minimumPostLength":"8","maximumPostLength":"32767","minimumTagsPerTopic":"0","maximumTagsPerTopic":"5","allowGuestSearching":"0","allowTopicsThumbnail":"0","registrationType":"normal","allowLocalLogin":"1","allowAccountDelete":"1","allowFileUploads":"0","maximumFileSize":"2048","minimumTitleLength":"3","maximumTitleLength":"255","minimumUsernameLength":"2","maximumUsernameLength":"16","minimumPasswordLength":"6","maximumSignatureLength":"255","maximumAboutMeLength":"1000","maximumProfileImageSize":"256","profileImageDimension":"128","requireEmailConfirmation":"0","profile:allowProfileImageUploads":"1","teaserPost":"last","theme:type":"local","theme:id":"nodebb-theme-persona","theme:staticDir":"","theme:templates":"","theme:src":""}

current phase: fixTopicTimestampsDone

current phase: fixTopicTimestampsStart

current phase: relockingTopicsDone

current phase: relockingTopicsStart

current phase: fixGroupsOwnersDone

current phase: fixGroupsOwnersStart

current phase: votesImportDone

Importing 0/0 votes took: 0.01 seconds

{"warn":"Current selected exporter does not implement getVotes function, skipping..."}

Importing 0 votes.

{"warn":"Current selected exporter does not implement getVotes function, skipping..."}

current phase: votesImportStart

current phase: fixPostsToPidsDone

current phase: fixPostsToPidsStart

current phase: fixCategoriesParentsDone

current phase: fixCategoriesParentsStart

Importing 680/680 posts took: 5.68 seconds

current phase: postsImportDone

Importing 680 posts.

current phase: postsImportStart

current phase: topicsImportDone

Importing 244/244 topics took: 8.17 seconds

Importing 244 topics.

current phase: topicsImportStart

Importing 0/0 messages took: 0.01 seconds

current phase: messagesImportDone

{"warn":"Current selected exporter does not implement getMessages function, skipping..."}

Importing 0 messages.

{"warn":"Current selected exporter does not implement getMessages function, skipping..."}

current phase: messagesImportStart

current phase: usersImportDone

Importing 0/0 users took: 0.11 seconds

Importing 0 users.

current phase: usersImportStart

current phase: categoriesImportDone

Importing 4/4 categories took: 1.30 seconds

Importing 4 categories.

current phase: categoriesImportStart

current phase: groupsImportDone

Importing 0/0 groups took: 0.01 seconds

Importing 0 groups.

current phase: groupsImportStart

current phase: resetGlobalsDone

current phase: deleteTmpImportedSetsAndObjectsDone

current phase: deleteTmpImportedSetsAndObjectsStart

current phase: resetGlobalsStart

current phase: purgeMessagesDone

current phase: purgeMessagesStart

current phase: purgeUsersDone

current phase: purgeUsersStart

current phase: purgeCategories+Topics+PostsDone

purgeCategories+Topics+PostsStart : [[error:no-privileges]]

current phase: purgeCategories+Topics+PostsStart

setup

installing: nodebb-plugin-import-wordpress

```

**Comment by akhoury** [comment]
something is weird, is it possible to take a look at your database? at least the structure?
if so, feel free to send me either a dump or access to your server at bentael@gmail.com

**Comment by singhnsk** [comment]
@akhoury I've sent you an email. Hopefully we can work out on an alternate instead of a complete access to the db.

**Comment by akhoury** [comment]
this is done
