### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by moebis** [a5mith/nodebb-plugin-import-wordpress#4]
It's not clear how to use this? Is this installed and run on the server running Wordpress/bbpress? or do we install this on the nodebb server? How do we bring the data over from bbpress into nodebb?

**Comment by akhoury** [comment]
nah you don't really install this, you install https://github.com/akhoury/nodebb-plugin-import and then you select the `nodebb-plugin-import-wordpress` from the drop down, at the "select the exporter" section, in the Pre Import Config

https://cloud.githubusercontent.com/assets/1398375/11704593/f667be60-9eb6-11e5-856c-bdfacde800bf.png
